export interface CloudSeaSite {
  id: string;
  name: string;
  province: string;
  area: string;
  latitude: number;
  longitude: number;
  altitude: number;
  viewpoint: string;
  description: string;
}

export const CLOUD_SEA_SITES: CloudSeaSite[] = [
  // --- 浙江及长三角网红顶流机位 ---
  {
    id: "cs-taizijian",
    name: "临安太子尖",
    province: "浙江",
    area: "杭州市临安区清凉峰镇",
    latitude: 30.124,
    longitude: 118.918,
    altitude: 1558,
    viewpoint: "太子尖顶峰观景台 / 浙西天池垭口",
    description: "浙西北最具人气的云海日出与星空圣地，公路直通海拔1400米垭口，轻徒步即可俯瞰茫茫云涛翻涌。",
  },
  {
    id: "cs-qianniugang",
    name: "临安牵牛岗",
    province: "浙江",
    area: "杭州市临安区深渡村",
    latitude: 30.082,
    longitude: 119.015,
    altitude: 1480,
    viewpoint: "牵牛岗气象雷达站 / 大明山顶观景台",
    description: "自驾直达顶峰的网红胜地，白色巨型气象雷达球耸立云海之巅，清晨日出云瀑奔流，夜拍银河拱桥极佳。",
  },
  {
    id: "cs-kuocangshan",
    name: "临海括苍山",
    province: "浙江",
    area: "台州市临海市括苍镇",
    latitude: 28.817,
    longitude: 120.916,
    altitude: 1382,
    viewpoint: "米筛浪极顶 / 风车公路观景台",
    description: "浙东第一高峰，全国最知名的巨型风车云海圣地，数十座白色风车在浩瀚云海与日出金光中若隐若现。",
  },
  {
    id: "cs-andingshan",
    name: "富阳安顶山",
    province: "浙江",
    area: "杭州市富阳区里山镇",
    latitude: 30.012,
    longitude: 120.088,
    altitude: 790,
    viewpoint: "天空之城观景平台 / 高山茶园",
    description: "杭州近郊自驾可达的网红茶山云海，富春江水汽蒸腾，清晨山顶俯瞰云雾铺满江谷盆地，如入天宫仙境。",
  },
  {
    id: "cs-fuzhishan",
    name: "上虞覆卮山",
    province: "浙江",
    area: "绍兴市上虞区岭南乡",
    latitude: 29.708,
    longitude: 120.952,
    altitude: 861,
    viewpoint: "千年梯田观景台 / 冰川石浪顶",
    description: "第四纪冰川石浪与千年梯田相映成趣，雨后初晴云雾如波涛漫卷梯田古村，摄影极富层次感。",
  },
  {
    id: "cs-damingshan",
    name: "临安大明山",
    province: "浙江",
    area: "杭州市临安区清凉峰镇",
    latitude: 30.046,
    longitude: 118.995,
    altitude: 1489,
    viewpoint: "悬空栈道 / 万松岭大平台",
    description: "“浙西小黄山”，千米绝壁悬空栈道穿梭于云海波涛之上，秋季满山红叶与白云瀑布交相辉映。",
  },
  {
    id: "cs-longwangshan",
    name: "安吉龙王山",
    province: "浙江",
    area: "湖州市安吉县章村镇",
    latitude: 30.402,
    longitude: 119.418,
    altitude: 1587,
    viewpoint: "龙王山顶主峰碑 / 黄浦江源头",
    description: "浙北第一高峰，黄浦江源头，原始森林密布，秋冬雨雪后常形成波澜壮阔的壮观云海与雾凇奇景。",
  },
  {
    id: "cs-tianhuangping",
    name: "安吉天荒坪",
    province: "浙江",
    area: "湖州市安吉县山川乡",
    latitude: 30.468,
    longitude: 119.593,
    altitude: 980,
    viewpoint: "江南天池观景台 / 抽水蓄能电站环道",
    description: "高山天池碧波荡漾，环湖公路与浩瀚竹海相接，水汽丰沛，常现平流雾与翻滚的竹海云海奇观。",
  },
  {
    id: "cs-huadingfeng",
    name: "天台华顶峰",
    province: "浙江",
    area: "台州市天台县",
    latitude: 29.248,
    longitude: 121.228,
    altitude: 1098,
    viewpoint: "华顶国家森林公园拜经台 / 归云亭",
    description: "天台山主峰，古云锦杜鹃林与千米高山云海相融，佛宗道源之地，清晨紫气东来、云烟如画。",
  },
  {
    id: "cs-wuyanling",
    name: "泰顺乌岩岭",
    province: "浙江",
    area: "温州市泰顺县",
    latitude: 27.702,
    longitude: 119.682,
    altitude: 1611,
    viewpoint: "白云尖极顶 / 原始次生林区",
    description: "浙南第一高峰白云尖，常年白云缭绕，水汽充沛，万木葱茏间云海奔流如银河倾泻。",
  },
  {
    id: "cs-donghaiyunding",
    name: "宁海东海云顶",
    province: "浙江",
    area: "宁波市宁海县茶山",
    latitude: 29.278,
    longitude: 121.562,
    altitude: 872,
    viewpoint: "茶山极顶摩天岭 / 桃花溪观景台",
    description: "紧依三门湾与象山港，海洋暖湿气流在此抬升凝聚，形成独一无二的山海相拥壮美海岛云海。",
  },
  {
    id: "cs-simingshan",
    name: "余姚四明山",
    province: "浙江",
    area: "宁波市余姚市大岚镇",
    latitude: 29.733,
    longitude: 121.152,
    altitude: 1018,
    viewpoint: "仰天湖平台 / 四明山地质公园",
    description: "江南绿肺与最美盘山公路，深秋红枫覆雪，清晨山谷盆地积蓄平流雾，宛若漂浮空中的红枫群岛。",
  },

  // --- 安徽与华东经典云海 ---
  {
    id: "cs-huangshan",
    name: "黄山光明顶",
    province: "安徽",
    area: "黄山市黄山区",
    latitude: 30.136,
    longitude: 118.172,
    altitude: 1860,
    viewpoint: "光明顶 / 始信峰 / 莲花峰",
    description: "黄山自古云海奇绝，东海、南海、西海、北海和天海五海相映，常伴佛光与日出。",
  },
  {
    id: "cs-taoling",
    name: "皖南川藏线桃岭",
    province: "安徽",
    area: "宣城市泾县桃岭村",
    latitude: 30.495,
    longitude: 118.665,
    altitude: 850,
    viewpoint: "六道湾观景台 / 幸福路垭口",
    description: "皖南川藏线核心险道，盘山公路在云雾山谷间蜿蜒盘旋，自驾云端，雨后初晴常有瀑布云漫过垭口。",
  },
  {
    id: "cs-guniujiang",
    name: "石台牯牛降",
    province: "安徽",
    area: "池州市石台县与祁门县交界",
    latitude: 30.088,
    longitude: 117.485,
    altitude: 1727,
    viewpoint: "大峰顶 / 严家古村后山观景台",
    description: "华东最后一片原始森林，峡谷险峻，清晨从千仞悬崖间升腾起的原始谷地云海苍茫无垠。",
  },
  {
    id: "cs-tianzhushan",
    name: "天柱山天柱峰",
    province: "安徽",
    area: "安庆市潜山市",
    latitude: 30.723,
    longitude: 116.452,
    altitude: 1488,
    viewpoint: "拜岳台 / 飞来峰 / 天柱峰前",
    description: "擎天一柱，花岗岩崩塌地貌，云蒸霞蔚之时如巨柱撑天定海。",
  },

  // --- 江苏名山低空平流云海 ---
  {
    id: "cs-toutuoling",
    name: "南京紫金山",
    province: "江苏",
    area: "南京市玄武区",
    latitude: 32.068,
    longitude: 118.848,
    altitude: 448,
    viewpoint: "头陀岭观景平台 / 紫金山天文台",
    description: "金陵古都城中山，秋冬季节江南水汽积聚，清晨常现壮观平流云海将紫金山顶化作孤岛，俯瞰城市天际线。",
  },
  {
    id: "cs-huishan",
    name: "无锡惠山",
    province: "江苏",
    area: "无锡市梁溪区",
    latitude: 31.572,
    longitude: 120.252,
    altitude: 329,
    viewpoint: "三茅峰观景台 / 头茅峰",
    description: "太湖之滨胜地，太湖丰沛水汽在清晨化作平流云海，城市摩天大楼在云浪中如竹笋破土而出。",
  },

  // --- 江西与华中名山 ---
  {
    id: "cs-wugongshan",
    name: "武功山金顶",
    province: "江西",
    area: "萍乡市芦溪县",
    latitude: 27.458,
    longitude: 114.175,
    altitude: 1918,
    viewpoint: "金顶观景台 / 吊马桩 / 白鹤峰",
    description: "十万亩高山草甸上的壮阔云海，雨后晴晨常有浩瀚云涛漫卷草甸。",
  },
  {
    id: "cs-sanqingshan",
    name: "三清山玉京峰",
    province: "江西",
    area: "上饶市玉山县",
    latitude: 28.908,
    longitude: 118.062,
    altitude: 1819,
    viewpoint: "玉京峰顶 / 南清园 / 阳光海岸",
    description: "花岗岩峰林仙峰，巨蟒出山、东方女神在翻滚奔腾的白云巨浪中若隐若现。",
  },
  {
    id: "cs-lushan",
    name: "庐山大月山",
    province: "江西",
    area: "九江市庐山市",
    latitude: 29.553,
    longitude: 115.987,
    altitude: 1474,
    viewpoint: "含鄱口 / 五老峰 / 小天池",
    description: "匡庐奇秀甲天下，含鄱口迎鄱阳湖丰沛水汽，晨昏云海变幻莫测、飞瀑奔涌。",
  },
  {
    id: "cs-tianmenshan",
    name: "张家界天门山",
    province: "湖南",
    area: "张家界市永定区",
    latitude: 29.052,
    longitude: 110.478,
    altitude: 1518,
    viewpoint: "天门洞开 / 鬼谷栈道 / 玻璃栈道",
    description: "拔地擎天的喀斯特孤峰，天门洞在漫漫云海吞吐之间如仙门乍现。",
  },
  {
    id: "cs-hengshan",
    name: "衡山祝融峰",
    province: "湖南",
    area: "衡阳市南岳区",
    latitude: 27.297,
    longitude: 112.697,
    altitude: 1300,
    viewpoint: "祝融殿 / 望日台",
    description: "南岳独秀，祝融峰高耸入云，水汽由湘江谷地抬升形成壮观南岳云海烟云。",
  },
  {
    id: "cs-enshicanyon",
    name: "恩施大峡谷",
    province: "湖北",
    area: "恩施州恩施市沐抚办事处",
    latitude: 30.412,
    longitude: 109.182,
    altitude: 1700,
    viewpoint: "一炷香观景台 / 绝壁悬崖栈道",
    description: "百里绝壁千仞孤峰，清晨谷底清江水汽剧烈升腾，云海填满万丈绝壁大峡谷，如梦如幻。",
  },
  {
    id: "cs-qiyueshan",
    name: "利川齐岳山",
    province: "湖北",
    area: "恩施州利川市",
    latitude: 30.228,
    longitude: 108.733,
    altitude: 1500,
    viewpoint: "风电观景台 / 齐岳山脊",
    description: "中国南方最大山地草场，风车群在汹涌云海中旋转，如梦似幻。",
  },
  {
    id: "cs-laojunshan",
    name: "老君山金顶",
    province: "河南",
    area: "洛阳市栾川县",
    latitude: 33.725,
    longitude: 111.642,
    altitude: 2217,
    viewpoint: "金顶道观群 / 马鬃岭",
    description: "“远赴人间惊鸿宴，一睹老君山盛颜”。金顶悬浮于茫茫云海仙境之中。",
  },

  // --- 川西与西南顶级云海天花板 ---
  {
    id: "cs-niubeishan",
    name: "雅安牛背山",
    province: "四川",
    area: "雅安市荥经县/甘孜州泸定县",
    latitude: 29.742,
    longitude: 102.325,
    altitude: 3660,
    viewpoint: "牛背山顶 360° 观景平台",
    description: "亚洲最大 360 度观景平台，蜀山之王贡嘎雪山与翻滚云海、瀑布云的极致殿堂。",
  },
  {
    id: "cs-dawaygenzha",
    name: "宝兴达瓦更扎",
    province: "四川",
    area: "雅安市宝兴县",
    latitude: 30.612,
    longitude: 102.733,
    altitude: 3866,
    viewpoint: "通天路观景台 / 顶峰营地",
    description: "通往神仙居住的地方，云顶日出金光照耀无垠云海，常年可见云海瀑布。",
  },
  {
    id: "cs-yuzixi",
    name: "康定鱼子西",
    province: "四川",
    area: "甘孜州康定市新都桥镇",
    latitude: 30.138,
    longitude: 101.482,
    altitude: 4200,
    viewpoint: "鱼子西星空露营地 / 秋名山观景台",
    description: "全网爆火的 360 度雪山观景平台，遥望雅拉雪山与折多山脉，夕阳晚霞与漫天云海大潮如梦似幻。",
  },
  {
    id: "cs-lenggacuo",
    name: "贡嘎冷嘎措",
    province: "四川",
    area: "甘孜州康定市帮木吉德村",
    latitude: 29.418,
    longitude: 101.558,
    altitude: 4530,
    viewpoint: "冷嘎措神湖畔 / 贡嘎倒影机位",
    description: "直面贡嘎主峰的高山神湖，云海翻涌于雪峰脚下，日照金山与雪山倒影在云海之上交相辉映。",
  },
  {
    id: "cs-zimeiyakou",
    name: "贡嘎子梅垭口",
    province: "四川",
    area: "甘孜州康定市",
    latitude: 29.588,
    longitude: 101.767,
    altitude: 4550,
    viewpoint: "子梅垭口观景平台",
    description: "直面蜀山之王贡嘎主峰最近的垭口，无敌雪山金山与脚下奔流不息的云海大潮。",
  },
  {
    id: "cs-emeishan",
    name: "峨眉山金顶",
    province: "四川",
    area: "乐山市峨眉山市",
    latitude: 29.525,
    longitude: 103.337,
    altitude: 3079,
    viewpoint: "金顶十方普贤圣像广场 / 舍身崖",
    description: "四大佛教名山，云海茫茫一望无际，佛光与圣灯更添庄严瑰丽。",
  },
  {
    id: "cs-fanjingshan",
    name: "梵净山红云金顶",
    province: "贵州",
    area: "铜仁市江口县",
    latitude: 27.915,
    longitude: 108.698,
    altitude: 2336,
    viewpoint: "红云金顶 / 蘑菇石 / 老金顶",
    description: "黔东灵山，蘑菇石屹立云海之上，云瀑倾泻如银河倒挂千沟万壑。",
  },
  {
    id: "cs-jiaozixueshan",
    name: "昆明轿子雪山",
    province: "云南",
    area: "昆明市禄劝县",
    latitude: 26.083,
    longitude: 102.833,
    altitude: 4223,
    viewpoint: "轿顶观景台 / 精绝冰瀑沿线",
    description: "滇中第一高峰，雪山耸峙于滇中平原，俯瞰云浪浩瀚与高山杜鹃。",
  },

  // --- 华南丹霞与高山奇观 ---
  {
    id: "cs-danxiashan",
    name: "韶关丹霞山",
    province: "广东",
    area: "韶关市仁化县",
    latitude: 25.038,
    longitude: 113.748,
    altitude: 408,
    viewpoint: "长老峰韶音亭 / 观日亭",
    description: "世界地质公园，红砂岩丹霞孤峰在洁白如絮的晨雾云海中卓立，宛如水墨丹青仙境。",
  },
  {
    id: "cs-jinzishan",
    name: "清远金子山",
    province: "广东",
    area: "清远市连山壮族瑶族自治县",
    latitude: 24.698,
    longitude: 112.012,
    altitude: 1417,
    viewpoint: "金子山通天梯 / 极顶玻璃观景台",
    description: "南岭奇峰，广东第一险峰，常年云蒸霞蔚，天梯步道直插云海之巅，冬春常现雾凇冰挂。",
  },

  // --- 华北、西北与东北名山 ---
  {
    id: "cs-taishan",
    name: "泰山玉皇顶",
    province: "山东",
    area: "泰安市泰山区",
    latitude: 36.255,
    longitude: 117.108,
    altitude: 1545,
    viewpoint: "日观峰 / 玉皇顶 / 瞻鲁台",
    description: "五岳独尊，泰山四大奇观之一的云海玉盘，清晨云雾如巨浪翻滚于齐鲁平原之上。",
  },
  {
    id: "cs-huashan",
    name: "华山南峰",
    province: "陕西",
    area: "渭南市华阴市",
    latitude: 34.478,
    longitude: 110.082,
    altitude: 2154,
    viewpoint: "南峰落雁 / 东峰朝阳台",
    description: "奇险天下第一山，绝壁险峰直插云霄，云海如潮水般拍打千仞绝壁。",
  },
  {
    id: "cs-taibaishan",
    name: "太白山拔仙台",
    province: "陕西",
    area: "宝鸡市太白县",
    latitude: 33.958,
    longitude: 107.767,
    altitude: 3767,
    viewpoint: "拔仙台 / 大爷海观景台",
    description: "秦岭主峰，南北气候分界线，关中平原水汽在此积聚成浩瀚翻滚的秦岭云海。",
  },
  {
    id: "cs-wulingshan",
    name: "承德雾灵山",
    province: "河北",
    area: "承德市兴隆县",
    latitude: 40.603,
    longitude: 117.483,
    altitude: 2118,
    viewpoint: "雾灵极顶观景台",
    description: "燕山山脉最高峰，京郊避暑胜地，常年云雾弥漫、雨后初晴云海吞吐。",
  },
  {
    id: "cs-donglingshan",
    name: "北京东灵山",
    province: "北京/河北",
    area: "门头沟区与涿鹿县交界",
    latitude: 39.971,
    longitude: 115.485,
    altitude: 2303,
    viewpoint: "灵山主峰标志碑",
    description: "北京第一高峰，亚高山草甸，雨后初晴常现漫漫云海淹没华北群峰。",
  },
  {
    id: "cs-zhagana",
    name: "迭部扎尕那",
    province: "甘肃",
    area: "甘南州迭部县",
    latitude: 34.250,
    longitude: 103.208,
    altitude: 3300,
    viewpoint: "达日观景台 / 仙女滩",
    description: "石城扎尕那，晨雾与山谷云海从石崖缝隙中升腾，宛如世外桃源。",
  },
  {
    id: "cs-changbaishan",
    name: "长白山天池",
    province: "吉林",
    area: "延边州安图县",
    latitude: 42.003,
    longitude: 128.058,
    altitude: 2691,
    viewpoint: "北坡天文峰 / 西坡主峰",
    description: "十六座奇峰环抱天池，峡谷云雾喷涌而上形成天池云海奇景。",
  },
  {
    id: "cs-jiuxianshan",
    name: "德化九仙山",
    province: "福建",
    area: "泉州市德化县",
    latitude: 25.702,
    longitude: 118.118,
    altitude: 1658,
    viewpoint: "气象站观景台 / 弥勒造像台",
    description: "闽南云海圣地，国家气象站所在地，高山云海、佛光与雾凇交替绽放。",
  },
];
