export interface CloudSeaSite {
  id: string;
  name: string;
  province: string;
  area: string;
  latitude: number;
  longitude: number;
  altitude: number;
  viewpoint: string;
  description: string;
}

export const CLOUD_SEA_SITES: CloudSeaSite[] = [
  {
    id: "cs-huangshan",
    name: "黄山光明顶",
    province: "安徽",
    area: "黄山市黄山区",
    latitude: 30.136,
    longitude: 118.172,
    altitude: 1860,
    viewpoint: "光明顶 / 始信峰 / 莲花峰",
    description: "黄山自古云海奇绝，东海、南海、西海、北海和天海五海相映，常伴佛光与日出。",
  },
  {
    id: "cs-wugongshan",
    name: "武功山金顶",
    province: "江西",
    area: "萍乡市芦溪县",
    latitude: 27.458,
    longitude: 114.175,
    altitude: 1918,
    viewpoint: "金顶观景台 / 吊马桩 / 白鹤峰",
    description: "十万亩高山草甸上的壮阔云海，雨后晴晨常有浩瀚云涛漫卷草甸。",
  },
  {
    id: "cs-niubeishan",
    name: "牛背山",
    province: "四川",
    area: "雅安市荥经县/甘孜州泸定县",
    latitude: 29.742,
    longitude: 102.325,
    altitude: 3660,
    viewpoint: "牛背山顶 360° 观景平台",
    description: "亚洲最大 360 度观景平台，蜀山之王贡嘎雪山与翻滚云海、瀑布云的极致殿堂。",
  },
  {
    id: "cs-dawaygenzha",
    name: "达瓦更扎",
    province: "四川",
    area: "雅安市宝兴县",
    latitude: 30.612,
    longitude: 102.733,
    altitude: 3866,
    viewpoint: "通天路观景台 / 顶峰营地",
    description: "通往神仙居住的地方，云顶日出金光照耀无垠云海，常年可见云海瀑布。",
  },
  {
    id: "cs-taishan",
    name: "泰山玉皇顶",
    province: "山东",
    area: "泰安市泰山区",
    latitude: 36.255,
    longitude: 117.108,
    altitude: 1545,
    viewpoint: "日观峰 / 玉皇顶 / 瞻鲁台",
    description: "五岳独尊，泰山四大奇观之一的云海玉盘，清晨云雾如巨浪翻滚于齐鲁平原之上。",
  },
  {
    id: "cs-huashan",
    name: "华山南峰",
    province: "陕西",
    area: "渭南市华阴市",
    latitude: 34.478,
    longitude: 110.082,
    altitude: 2154,
    viewpoint: "南峰落雁 / 东峰朝阳台",
    description: "奇险天下第一山，绝壁险峰直插云霄，云海如潮水般拍打千仞绝壁。",
  },
  {
    id: "cs-laojunshan",
    name: "老君山金顶",
    province: "河南",
    area: "洛阳市栾川县",
    latitude: 33.725,
    longitude: 111.642,
    altitude: 2217,
    viewpoint: "金顶道观群 / 马鬃岭",
    description: "“远赴人间惊鸿宴，一睹老君山盛颜”。金顶悬浮于茫茫云海仙境之中。",
  },
  {
    id: "cs-emeishan",
    name: "峨眉山金顶",
    province: "四川",
    area: "乐山市峨眉山市",
    latitude: 29.525,
    longitude: 103.337,
    altitude: 3079,
    viewpoint: "金顶十方普贤圣像广场 / 舍身崖",
    description: "四大佛教名山，云海茫茫一望无际，佛光与圣灯更添庄严瑰丽。",
  },
  {
    id: "cs-lushan",
    name: "庐山大月山",
    province: "江西",
    area: "九江市庐山市",
    latitude: 29.553,
    longitude: 115.987,
    altitude: 1474,
    viewpoint: "含鄱口 / 五老峰 / 小天池",
    description: "匡庐奇秀甲天下，含鄱口迎鄱阳湖丰沛水汽，晨昏云海变幻莫测、飞瀑奔涌。",
  },
  {
    id: "cs-tianmenshan",
    name: "张家界天门山",
    province: "湖南",
    area: "张家界市永定区",
    latitude: 29.052,
    longitude: 110.478,
    altitude: 1518,
    viewpoint: "天门洞开 / 鬼谷栈道 / 玻璃栈道",
    description: "拔地擎天的喀斯特孤峰，天门洞在漫漫云海吞吐之间如仙门乍现。",
  },
  {
    id: "cs-fanjingshan",
    name: "梵净山红云金顶",
    province: "贵州",
    area: "铜仁市江口县",
    latitude: 27.915,
    longitude: 108.698,
    altitude: 2336,
    viewpoint: "红云金顶 / 蘑菇石 / 老金顶",
    description: "黔东灵山，蘑菇石屹立云海之上，云瀑倾泻如银河倒挂千沟万壑。",
  },
  {
    id: "cs-sanqingshan",
    name: "三清山玉京峰",
    province: "江西",
    area: "上饶市玉山县",
    latitude: 28.908,
    longitude: 118.062,
    altitude: 1819,
    viewpoint: "玉京峰顶 / 南清园 / 阳光海岸",
    description: "花岗岩峰林仙峰，巨蟒出山、东方女神在翻滚奔腾的白云巨浪中若隐若现。",
  },
  {
    id: "cs-yandangshan",
    name: "雁荡山百岗尖",
    province: "浙江",
    area: "温州市乐清市",
    latitude: 28.375,
    longitude: 121.054,
    altitude: 1150,
    viewpoint: "百岗尖主峰 / 灵峰合掌",
    description: "东南第一山，靠近东海暖湿气流，山海相映间云雾腾跃百岗尖。",
  },
  {
    id: "cs-tianzhushan",
    name: "天柱山天柱峰",
    province: "安徽",
    area: "安庆市潜山市",
    latitude: 30.723,
    longitude: 116.452,
    altitude: 1488,
    viewpoint: "拜岳台 / 飞来峰 / 天柱峰前",
    description: "擎天一柱，花岗岩崩塌地貌，云蒸霞蔚之时如巨柱撑天定海。",
  },
  {
    id: "cs-wulingshan",
    name: "雾灵山顶",
    province: "河北",
    area: "承德市兴隆县",
    latitude: 40.603,
    longitude: 117.483,
    altitude: 2118,
    viewpoint: "雾灵极顶观景台",
    description: "燕山山脉最高峰，京郊避暑胜地，常年云雾弥漫、雨后初晴云海吞吐。",
  },
  {
    id: "cs-jiaozixueshan",
    name: "轿子雪山",
    province: "云南",
    area: "昆明市禄劝县",
    latitude: 26.083,
    longitude: 102.833,
    altitude: 4223,
    viewpoint: "轿顶观景台 / 精绝冰瀑沿线",
    description: "滇中第一高峰，雪山耸峙于滇中平原，俯瞰云浪浩瀚与高山杜鹃。",
  },
  {
    id: "cs-zimeiyakou",
    name: "贡嘎子梅垭口",
    province: "四川",
    area: "甘孜州康定市",
    latitude: 29.588,
    longitude: 101.767,
    altitude: 4550,
    viewpoint: "子梅垭口观景平台",
    description: "直面蜀山之王贡嘎主峰最近的垭口，无敌雪山金山与脚下奔流不息的云海大潮。",
  },
  {
    id: "cs-qiyueshan",
    name: "齐岳山",
    province: "湖北",
    area: "恩施州利川市",
    latitude: 30.228,
    longitude: 108.733,
    altitude: 1500,
    viewpoint: "风电观景台 / 齐岳山脊",
    description: "中国南方最大山地草场，风车群在汹涌云海中旋转，如梦似幻。",
  },
  {
    id: "cs-hengshan",
    name: "衡山祝融峰",
    province: "湖南",
    area: "衡阳市南岳区",
    latitude: 27.297,
    longitude: 112.697,
    altitude: 1300,
    viewpoint: "祝融殿 / 望日台",
    description: "南岳独秀，祝融峰高耸入云，水汽由湘江谷地抬升形成壮观南岳云海烟云。",
  },
  {
    id: "cs-changbaishan",
    name: "长白山天池",
    province: "吉林",
    area: "延边州安图县",
    latitude: 42.003,
    longitude: 128.058,
    altitude: 2691,
    viewpoint: "北坡天文峰 / 西坡主峰",
    description: "十六座奇峰环抱天池，峡谷云雾喷涌而上形成天池云海奇景。",
  },
  {
    id: "cs-taibaishan",
    name: "太白山拔仙台",
    province: "陕西",
    area: "宝鸡市太白县",
    latitude: 33.958,
    longitude: 107.767,
    altitude: 3767,
    viewpoint: "拔仙台 / 大爷海观景台",
    description: "秦岭主峰，南北气候分界线，关中平原水汽在此积聚成浩瀚翻滚的秦岭云海。",
  },
  {
    id: "cs-jiuxianshan",
    name: "德化九仙山",
    province: "福建",
    area: "泉州市德化县",
    latitude: 25.702,
    longitude: 118.118,
    altitude: 1658,
    viewpoint: "气象站观景台 / 弥勒造像台",
    description: "闽南云海圣地，国家气象站所在地，高山云海、佛光与雾凇交替绽放。",
  },
  {
    id: "cs-zhagana",
    name: "扎尕那达日观景台",
    province: "甘肃",
    area: "甘南州迭部县",
    latitude: 34.250,
    longitude: 103.208,
    altitude: 3300,
    viewpoint: "达日观景台 / 仙女滩",
    description: "石城扎尕那，晨雾与山谷云海从石崖缝隙中升腾，宛如世外桃源。",
  },
  {
    id: "cs-donglingshan",
    name: "北京东灵山",
    province: "北京/河北",
    area: "门头沟区与涿鹿县交界",
    latitude: 39.971,
    longitude: 115.485,
    altitude: 2303,
    viewpoint: "灵山主峰标志碑",
    description: "北京第一高峰，亚高山草甸，雨后初晴常现漫漫云海淹没华北群峰。",
  },
];
